import 'package:flutter/material.dart';
import 'package:flutter_challenge_dog_api/presentation/pages/navpages/second.dart';

import '../presentation/pages/navpages/favorite.dart';
import '../presentation/pages/navpages/home.dart';
import '../presentation/pages/navpages/person.dart';

List<Widget> pages = [
  const HomePage(),
  const SecondPage(),
  const FavoritePage(),
  const PersonPage(),
];

List<String> dogBreeds = [
  'akita',
  'affenpinscher',
  'african',
  'stbernard',
  "sharpei",
  'airedale',
  'appenzeller',
  'australian',
  'basenji',
  'beagle',
  'bulldog',
  'babrador',
  'segugio',
  'shiba',
  'bluetick',
  'hound',
  'buhund',
  'cockapoo',
  "husky",
  'mastiff',
  "papillon",
  'puggle',
  'schipperke',
  'tervuren',
  'vizsla',
  'waterdog',
  'weimaraner',
  'whippet',
  'wolfhound',
  'havanese',
  'terrier',
  'springer',
  'dhole',
  'dingo',
  'doberman',
  'entlebucher',
  'eskimo',
  'finnish'
];


final Map<String, List<String>> breedData = {
    "affenpinscher": [],
    "african": [],
    "airedale": [],
    "akita": [],
    "appenzeller": [],
    "australian": ["shepherd"],
    "basenji": [],
    "beagle": [],
    "bluetick": [],
    "borzoi": [],
    "bouvier": [],
    "boxer": [],
    "brabancon": [],
    "briard": [],
    "buhund": ["norwegian"],
    "bulldog": ["boston", "english", "french"],
    "bullterrier": ["staffordshire"],
    "cattledog": ["australian"],
    "cavapoo": [],
    "chihuahua": [],
    "chow": [],
    "clumber": [],
    "cockapoo": [],
    "collie": ["border"],
    "coonhound": [],
    "corgi": ["cardigan"],
    "cotondetulear": [],
    "dachshund": [],
    "dalmatian": [],
    "dane": ["great"],
    "deerhound": ["scottish"],
    "dhole": [],
    "dingo": [],
    "doberman": [],
    "elkhound": ["norwegian"],
    "entlebucher": [],
    "eskimo": [],
    "finnish": ["lapphund"],
    "frise": ["bichon"],
    "germanshepherd": [],
    "greyhound": ["italian"],
    "groenendael": [],
    "havanese": [],
    "hound": ["afghan", "basset", "blood", "english", "ibizan", "plott", "walker"],
    "husky": [],
    "keeshond": [],
    "kelpie": [],
    "komondor": [],
    "kuvasz": [],
    "labradoodle": [],
    "labrador": [],
    "leonberg": [],
    "lhasa": [],
    "malamute": [],
    "malinois": [],
    "maltese": [],
    "mastiff": ["bull", "english", "tibetan"],
    "mexicanhairless": [],
    "mix": [],
    "mountain": ["bernese", "swiss"],
    "newfoundland": [],
    "otterhound": [],
    "ovcharka": ["caucasian"],
    "papillon": [],
    "pekinese": [],
    "pembroke": [],
    "pinscher": ["miniature"],
    "pitbull": [],
    "pointer": ["german", "germanlonghair"],
    "pomeranian": [],
    "poodle": ["medium", "miniature", "standard", "toy"],
    "pug": [],
    "puggle": [],
    "pyrenees": [],
    "redbone": [],
    "retriever": ["chesapeake", "curly", "flatcoated", "golden"],
    "ridgeback": ["rhodesian"],
    "rottweiler": [],
    "saluki": [],
    "samoyed": [],
    "schipperke": [],
    "schnauzer": ["giant", "miniature"],
    "segugio": ["italian"],
    "setter": ["english", "gordon", "irish"],
    "sharpei": [],
    "sheepdog": ["english", "shetland"],
    "shiba": [],
    "shihtzu": [],
    "spaniel": ["blenheim", "brittany", "cocker", "irish", "japanese", "sussex", "welsh"],
    "spitz": ["japanese"],
    "springer": ["english"],
    "stbernard": [],
    "terrier": [
      "american",
      "australian",
      "bedlington",
      "border",
      "cairn",
      "dandie",
      "fox",
      "irish",
      "kerryblue",
      "lakeland",
      "norfolk",
      "norwich",
      "patterdale",
      "russell",
      "scottish",
      "sealyham",
      "silky",
      "tibetan",
      "toy",
      "welsh",
      "westhighland",
      "wheaten",
      "yorkshire"
    ],
    "tervuren": [],
    "vizsla": [],
    "waterdog": ["spanish"],
    "weimaraner": [],
    "whippet": [],
    "wolfhound": ["irish"]
  };
  List<String> breedKeys = breedData.keys.toList();
  